/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeviceInfo: typeof import('./src/components/DeviceInfo/index.vue')['default']
    FlvPlayer: typeof import('./src/components/FlvPlayer/index.vue')['default']
    Handle: typeof import('./src/components/play/handle/index.vue')['default']
    HandleBtn: typeof import('./src/components/play/handle/HandleBtn.vue')['default']
    HlsPlayer: typeof import('./src/components/HlsPlayer/index.vue')['default']
    MapView: typeof import('./src/components/MapView/index.vue')['default']
    PickPlaySource: typeof import('./src/components/play/PickPlaySource.vue')['default']
    Play: typeof import('./src/components/play/index.vue')['default']
    PlayInstance: typeof import('./src/components/play/PlayInstance.vue')['default']
    Setting: typeof import('./src/components/Setting/index.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanIcon: typeof import('vant/es')['Icon']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanTag: typeof import('vant/es')['Tag']
  }
}
