/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Handle: typeof import('./src/components/play/handle/index.vue')['default']
    HandleBtn: typeof import('./src/components/play/handle/HandleBtn.vue')['default']
    PickPlaySource: typeof import('./src/components/play/PickPlaySource.vue')['default']
    Play: typeof import('./src/components/play/index.vue')['default']
    PlayInstance: typeof import('./src/components/play/PlayInstance.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
